name: Applying autofixes

on:
  pull_request:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install hatch
        run: python -m pip install hatch
      - name: Run Python formatter
        run: python -m hatch run ufmt format
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "www/package-lock.json"
      - run: npm install
        working-directory: www
      - name: Run prettier
        run: npx prettier -w .
        working-directory: www
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
