name: Indexer Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0-alpha - 3.11"
          cache: "pip"
          cache-dependency-path: "www/package-lock.json"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run tests
        run: uv run poe cov
      - name: Type check
        run: uv run poe check-types
