name: Update Index
on:
  workflow_dispatch:
  schedule:
    - cron: "34 * * * *"
jobs:
  update_index:
    environment: r2-prod
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install hatch
        run: python -m pip install hatch
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/65154078780/locations/global/workloadIdentityPools/github/providers/py-wtf
          service_account: pypinfo@pypinfo-214114.iam.gserviceaccount.com
          project_id: pypinfo-214114
          export_environment_variables: true
      - name: Index
        run: set -x; python -m hatch run py-wtf index-since --since "$(date -d '1hour ago' '+%Y-%m-%d %H:%M:%S')" _index
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      - name: Compress index
        run: gzip -9 _index/*.json
      - name: Upload
        run: |
          set -e
          aws s3 sync --endpoint-url ${{ secrets.R2_ENDPOINT }} \
            _index s3://${{secrets.R2_BUCKET}}/_index \
            --exclude '*' --include '*.json.gz' \
            --no-guess-mime-type --content-encoding gzip \
            --content-type application/json
          aws s3 cp --endpoint-url ${{ secrets.R2_ENDPOINT }} \
            _index/.metadata s3://${{secrets.R2_BUCKET}}/_index/.metadata \
            --content-type application/json
